spring:
  application:
    name: nookio-api
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}_${ENVIRONMENT}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  threads:
    virtual:
      enabled: true