spring:
  application:
    name: nookio-api
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}_${ENVIRONMENT}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  threads:
    virtual:
      enabled: true

clients:
  api-id: ${API_ID}
  analytics:
    url: ${ANALYTICS_SERVICE_URL:http://localhost:8081}${BASE_ENDPOINT}
    transport: ${ANALYTICS_TRANSPORT:http}
  payments:
    url: ${PAYMENTS_SERVICE_URL:http://localhost:8082}${BASE_ENDPOINT}
    transport: ${PAYMENTS_TRANSPORT:http}
